### ISSUE TITLE
environment.yml will not build with newest anaconda on MacOS 10.15.3

### ISSUE THREAD

**Issue by jasongfleischer** [jcamunas/patchseq#2]
Using the newest anaconda (recently ran conda update conda; conda update anaconda), the supplied environment.yml fails with

  File "/Users/jfleischer/opt/anaconda3/envs/patchseq/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 210, in install
    assert (not ioloop.IOLoop.initialized()) or \
AttributeError: type object 'IOLoop' has no attribute 'initialized'

Googling it looks like this is maybe a conflict between packages that arose at one point with Jupyter. Recommended is to let conda handle it by installing pyzmq 

conda install -c anaconda pyzmq

I tried this  by changing the environment.yml (moving pyzmq line from pip to conda section).  This didn't help, and just resulted in one of the longest attempts to mediate conflicts I have ever dealt with before it ultimately failed.

Log is below...

-----

 

$ conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages
jpeg-9b              | 236 KB    | ###################################################################################################################################################### | 100% 
libcxx-10.0.0        | 1.0 MB    | ###################################################################################################################################################### | 100% 
icu-58.2             | 22.6 MB   | ###################################################################################################################################################### | 100% 
libedit-3.1.20181209 | 159 KB    | ###################################################################################################################################################### | 100% 
readline-7.0         | 393 KB    | ###################################################################################################################################################### | 100% 
yaml-0.1.7           | 80 KB     | ###################################################################################################################################################### | 100% 
libffi-3.2.1         | 43 KB     | ###################################################################################################################################################### | 100% 
gmp-6.1.2            | 734 KB    | ###################################################################################################################################################### | 100% 
prometheus_client-0. | 42 KB     | ###################################################################################################################################################### | 100% 
zlib-1.2.11          | 105 KB    | ###################################################################################################################################################### | 100% 
blas-1.0             | 5 KB      | ###################################################################################################################################################### | 100% 
libgfortran-3.0.1    | 495 KB    | ###################################################################################################################################################### | 100% 
decorator-4.4.2      | 14 KB     | ###################################################################################################################################################### | 100% 
bzip2-1.0.8          | 104 KB    | ###################################################################################################################################################### | 100% 
gettext-0.19.8.1     | 3.4 MB    | ###################################################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: / b''
/ b''
| b'Enabling: jupyter_nbextensions_configurator\n- Writing config: /Users/jfleischer/opt/anaconda3/envs/patchseq/etc/jupyter\n    - Validating...\n      jupyter_nbextensions_configurator 0.4.0 \x1b[32mOK\x1b[0m\nEnabling notebook nbextension nbextensions_configurator/config_menu/main...\nEnabling tree nbextension nbextensions_configurator/tree_tab/main...\n'
/ b'/Users/jfleischer/opt/anaconda3/envs/patchseq/lib/python3.6/site-packages/zmq/backend/cffi/__pycache__/_cffi_ext.c:243:3: warning: code will never be executed [-Wunreachable-code]\n  _cffi_check__zmq_msg_t(0);\n  ^~~~~~~~~~~~~~~~~~~~~~\n/Users/jfleischer/opt/anaconda3/envs/patchseq/lib/python3.6/site-packages/zmq/backend/cffi/__pycache__/_cffi_ext.c:276:3: warning: code will never be executed [-Wunreachable-code]\n  _cffi_check__zmq_pollitem_t(0);\n  ^~~~~~~~~~~~~~~~~~~~~~~~~~~\n2 warnings generated.\nTraceback (most recent call last):\n  File "/Users/jfleischer/opt/anaconda3/envs/patchseq/bin/jupyter-contrib-nbextension", line 4, in <module>\n    import jupyter_contrib_nbextensions.application\n  File "/Users/jfleischer/opt/anaconda3/envs/patchseq/lib/python3.6/site-packages/jupyter_contrib_nbextensions/application.py", line 15, in <module>\n    from jupyter_contrib_nbextensions.install import (\n  File "/Users/jfleischer/opt/anaconda3/envs/patchseq/lib/python3.6/site-packages/jupyter_contrib_nbextensions/install.py", line 17, in <module>\n    from notebook.notebookapp import list_running_servers\n  File "/Users/jfleischer/opt/anaconda3/envs/patchseq/lib/python3.6/site-packages/notebook/notebookapp.py", line 50, in <module>\n    ioloop.install()\n  File "/Users/jfleischer/opt/anaconda3/envs/patchseq/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 210, in install\n    assert (not ioloop.IOLoop.initialized()) or \\\nAttributeError: type object \'IOLoop\' has no attribute \'initialized\'\n'
done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'conda-forge::jupyter_contrib_nbextensions-0.4.0-py36_0'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::jupyter_contrib_nbextensions-0.4.0-py36_0
location of failed script: /Users/jfleischer/opt/anaconda3/envs/patchseq/bin/.jupyter_contrib_nbextensions-post-link.sh
==> script messages <==
/Users/jfleischer/opt/anaconda3/envs/patchseq/lib/python3.6/site-packages/zmq/backend/cffi/__pycache__/_cffi_ext.c:243:3: warning: code will never be executed [-Wunreachable-code]
  _cffi_check__zmq_msg_t(0);
  ^~~~~~~~~~~~~~~~~~~~~~
/Users/jfleischer/opt/anaconda3/envs/patchseq/lib/python3.6/site-packages/zmq/backend/cffi/__pycache__/_cffi_ext.c:276:3: warning: code will never be executed [-Wunreachable-code]
  _cffi_check__zmq_pollitem_t(0);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
2 warnings generated.
Traceback (most recent call last):
  File "/Users/jfleischer/opt/anaconda3/envs/patchseq/bin/jupyter-contrib-nbextension", line 4, in <module>
    import jupyter_contrib_nbextensions.application
  File "/Users/jfleischer/opt/anaconda3/envs/patchseq/lib/python3.6/site-packages/jupyter_contrib_nbextensions/application.py", line 15, in <module>
    from jupyter_contrib_nbextensions.install import (
  File "/Users/jfleischer/opt/anaconda3/envs/patchseq/lib/python3.6/site-packages/jupyter_contrib_nbextensions/install.py", line 17, in <module>
    from notebook.notebookapp import list_running_servers
  File "/Users/jfleischer/opt/anaconda3/envs/patchseq/lib/python3.6/site-packages/notebook/notebookapp.py", line 50, in <module>
    ioloop.install()
  File "/Users/jfleischer/opt/anaconda3/envs/patchseq/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 210, in install
    assert (not ioloop.IOLoop.initialized()) or \
AttributeError: type object 'IOLoop' has no attribute 'initialized'

==> script output <==
stdout: 
stderr: 
return code: 1

()

-------

**Comment by jasongfleischer** [comment]
However, I was able to use the newest anaconda base with a few additions:
$ conda update conda
$ conda update anaconda
$ conda env --clone base -n patchseq
$ conda activate patchseq
$ pip install singlet
$ conda install xarray

(Conda didn’t seem to know singlet but pip did)

This is not yet tested to give the same results as your paper.  Will keep you up to date.

**Comment by jasongfleischer** [comment]
update: I've found that additional packages are required in other notebooks.  Execution is error-free when you add
$ conda install -c conda-forge scikit-plot 
$ conda install -c conda-forge imbalanced-learn==0.6. 

Note imblearn current version 0.7 does not seem to work with the sklearn 0.22 in Fig6 notebook.  Searching for the error it seems like this is a regular occurrence with previous versions; imblearn seems to always require newest sklearn.  I am wary of upgrading the conda base sklearn (been bitten before by that, it introduces other potential package difficulties). So I downgraded imblearn to 0.6 and everything works fine.  and v0.6 is > than the 0.4 spec'd in the current environment.yml
